development:
  port: 30304
  rpc: true
  rpcaddr: 127.0.0.1
  rpcport: 8101
  rpccorsdomain: http://127.0.0.1:8000
  genesis: config/development/genesis.json
  datadir: datadir/development/
  networkid: 5473
  unlock: f7ecf10c8ebf8ecc911d076bb4532494c4924de7
  password: config/development/password
  nodiscover: true
production:
  rpc: true
  rpcaddr: 127.0.0.1
  rpcport: 8545
  rpccorsdomain: http://127.0.0.1:8001
  unlock: dc99b79555385ab2fe0ff28c3c954a07b28aac5e
  password: config/production/password